# Generated by Django 3.2.9 on 2022-01-09 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listings_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 9, 7, 35, 28, 518537)),
        ),
    ]
