# Generated by Django 3.2.9 on 2022-01-09 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
