# Generated by Django 3.2.9 on 2022-01-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20220111_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='auctions.Listings'),
        ),
    ]
