# Generated by Django 3.2.9 on 2022-01-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_watchlist_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bids',
        ),
        migrations.AddField(
            model_name='listings',
            name='bids',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, to='auctions.Listings'),
        ),
    ]
