# Generated by Django 3.2.9 on 2022-01-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20220117_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bids',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
