# Generated by Django 3.2.9 on 2022-01-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listings_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bids',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='items',
            field=models.ManyToManyField(blank=True, to='auctions.Listings'),
        ),
    ]
