# Generated by Django 3.2.9 on 2022-01-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20220117_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bids',
        ),
    ]
